_SIM_DAY = 86_400.0
REMINDER_THRESHOLD_SIM_SECONDS = 4 * _SIM_DAY
PDF_PHOTO_REMINDER_THRESHOLD_SIM_SECONDS = 8 * _SIM_DAY
QUIET_MARGIN_SIM_SECONDS = 2 * _SIM_DAY
PDF_PHOTO_QUIET_MARGIN_SIM_SECONDS = 3 * _SIM_DAY
NEGOTIATION_REPLY_SIM_DAYS = 1.0
ESCALATION_SETTLE_SIM_SECONDS = _SIM_DAY
PDF_PHOTO_SUPPLIER_IDS = frozenset({"p03", "p04"})
VALIDITY_ALARM_MARGIN_DAYS = 2.0


def reminder_threshold_seconds(supplier_id: str) -> float:
    if supplier_id in PDF_PHOTO_SUPPLIER_IDS:
        return PDF_PHOTO_REMINDER_THRESHOLD_SIM_SECONDS
    return REMINDER_THRESHOLD_SIM_SECONDS


def quiet_margin_seconds(supplier_id: str) -> float:
    if supplier_id in PDF_PHOTO_SUPPLIER_IDS:
        return PDF_PHOTO_QUIET_MARGIN_SIM_SECONDS
    return QUIET_MARGIN_SIM_SECONDS
